version: "1.0.0"

services:
  web:
    build: .
    command:  >
      bash -c "
        python manage.py migrate &&
        python manage.py createsuperuser --noinput --username admin --email admin@example.com --password adminpassword &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"